- .github/workflows/translation_pull.yml
- .github/workflows/translation_push.yml
- crowdin.yml
Changes:
Triggering translation workflow for Crowdin to test automated Translation push and pull
> chore: trigger translation workflow

- i18n/en/code.json
- i18n/en/docusaurus-plugin-content-docs/current.json
- Triggering translation workflow for Crowdin to test automated Translation push and pull
> chore: trigger translation push

- .github/workflows/translation_pull.yml
- .github/workflows/translation_push.yml
Changes:### 
- removed write-all permission from translation push workflow
- removed write-all permission from translation pull workflow
> fix: remove write-all permission from translation workflows

- .github/workflows/translation_pull.yml
- Remove the top-level permission
- Added job-level permission
- Only added pull-request and contents permission
> fix: add permission to job level

- src/components/Footer/index.tsx
- src/components/UserNavbarItem/item.desktop.tsx
- src/features/Apiexplorer/Dropdown/DropdownList/index.tsx
- src/features/Apiexplorer/LoginDialog/index.tsx
- src/features/Apiexplorer/RequestJSONBox/index.tsx
- src/features/Apiexplorer/SubscribeRenderer/index.tsx
- src/features/Apiexplorer/ValidDialog/index.tsx
- src/features/Auth/Login/Login.tsx
- src/features/Endpoint/Endpoint.tsx
- src/features/Home/ApiFeatures/ApiFeatures.tsx
- src/features/Home/Carousel/Carousel.tsx
- src/features/Home/ClientLibraries/ClientLibraries.tsx
- src/features/Home/GetStarted/GetStarted.tsx
- src/features/Home/HeroHeader/HeroHeader.tsx
- src/features/Home/WaysToEarn/WaysToEarn.tsx
- src/features/dashboard/components/ApiTokenCard/index.tsx
- src/features/dashboard/components/ApiTokenForm/api-token.form.tsx
- src/features/dashboard/components/ApiTokenTable/CopyTokenDialog/index.tsx
- src/features/dashboard/components/AppForm/index.tsx
- src/features/dashboard/components/AppsTable/app-actions.cell.tsx
- src/features/dashboard/components/Dialogs/RegisterAppDialogError/index.tsx
- src/features/dashboard/components/Dialogs/RegisterAppDialogSuccess/index.tsx
- src/features/dashboard/components/Dialogs/UpdateAppDialog/index.tsx
- src/features/dashboard/components/NoApps/index.tsx
- src/features/dashboard/components/Tabs/index.tsx
- src/features/dashboard/manage-tokens/index.tsx
Changes### 
- Added Translate wrapper around the texts for translation
- Removed few unused imports and variables
> [DAPI] chore: add Translate wrapper

- src/utils/index.ts
Changes### 
- Added binary.sx in the white listed domain list to show protected components in feature branch test link
> Shafin/chore: add binary.sx in domain

- src/components/Header/Header.module.scss
- src/styles/index.scss
Ensuring that the navbar and the navtop sticks to the top when scrolling
> Agrim/dapi 543/navbarsticky

- package-lock.json
- package.json
- src/components/CustomCheckbox/custom_checkbox.module.scss
- src/contexts/app-manager/app-manager.context.tsx
- src/contexts/app-manager/app-manager.provider.tsx
- src/features/dashboard/components/AppDashboardContainer/index.tsx
- src/features/dashboard/components/AppForm/__tests__/app-form.test.tsx
- src/features/dashboard/components/AppRegister/app-register.scss
- src/features/dashboard/components/AppRegister/index.tsx
- src/features/dashboard/components/AppRegister/types.ts
- src/features/dashboard/components/AppsTable/app-actions.cell.tsx
- src/features/dashboard/components/AppsTable/apps-table.scss
- src/features/dashboard/components/AppsTable/index.tsx
- src/features/dashboard/components/Dialogs/UpdateAppDialog/index.tsx
- src/features/dashboard/components/StepperTextField/index.tsx
- src/features/dashboard/components/StepperTextField/stepper-text-field.scss
- src/features/dashboard/components/Table/copy-text.cell.scss
- src/features/dashboard/manage-dashboard/__tests__/manage-dashboard.test.tsx
- src/features/dashboard/manage-dashboard/index.tsx
- src/features/dashboard/types.ts
- src/features/dashboard/update-app/AppUpdateForm/app-update-form.scss
- src/features/dashboard/update-app/AppUpdateForm/index.tsx
- src/features/dashboard/update-app/index.tsx
- Implemented the app update page
- unified the error messages for app name and updated previous test cases
- added the updating app into the context to pass it to the updating screen
> [DAPI] shafin/chore implement app update page

- src/features/Home/HeroHeader/HeroHeader.tsx
- Fix the link issue in the dashboard that was creating issue in french
> [DAPI] chore: fix doc link in dashboard

- i18n/en/code.json
- src/features/Home/ApiFeatures/ApiFeatures.tsx
- src/features/dashboard/components/ApiTokenTable/DeleteTokenDialog/index.tsx
- src/features/dashboard/components/Dialogs/DeleteAppDialog/index.tsx
Changes### 
- Added missing translations in the landing page and dashboard
- Run write-translation to generate strings
> chore: add missing translations

- src/components/Footer/index.tsx
Changes### 
- Removed the in-context translation as it is blocking the UI and testing
> [DAPI] Shafin/dapi 578/chore remove in context translation

- i18n/en/code.json
- src/features/dashboard/components/ApiTokenForm/CreateTokenField/CustomErrors/index.tsx
- src/features/dashboard/components/ApiTokenForm/api-token.form.tsx
- src/features/dashboard/components/ApiTokenTable/CopyButton/index.tsx
- src/features/dashboard/components/ApiTokenTable/CopyTokenDialog/index.tsx
- src/features/dashboard/components/Dialogs/TokenCreationDialogSuccess/index.tsx
Changes### 
- Missing translation from token creation journey is added
> [DAPI] Shafin/chore: add missing translations

- src/features/Home/ClientLibraries/ClientLibraries.tsx
Changes### 
- Add missing translation in the landing page
> [DAPI] shafin/chore: add missing translation

- i18n/en/code.json
- src/components/AccountSwitcher/index.tsx
- src/features/Home/ClientLibraries/__tests__/ClientLibraries.test.tsx
- src/features/Home/GetStarted/GetStarted.tsx
- Added missing translation in the landing page
> chore: add missing translation

- src/styles/index.scss
- Added custom css for json tree view to fix mobile view overflow
> fix: Spike - Overflow on Mobile Responsive

- .gitignore
- Add env files in gitignore to reduce security vulnerabilities
> chore: add env in gitignore

- docusaurus.config.js
- package-lock.json
- Removed last update author name from config
> shafin/chore: change config to remove author name

- README.md
- package.json
- Updated scripts as follows
Added `npm run bootstrap` to clean install and build -- prepare for local run
Added `npm run dev` to easy start the project
- Updated readme with the new scripts
> sandeep/chore: updated scripts and readme

- package.json
- updated engine version to 20
- updated package version to 1.0.0
- moved engine config to the top
> chore: :fire: updated engine version

- .github/workflows/release_production.yml
- Add webhook URL for workflow `publish_to_vercel_DR` to fix the slack notification failing issue
> shafin/chore: fix github action for DR slack notification failure

- i18n/en/code.json
- i18n/en/docusaurus-theme-classic/navbar.json
- src/components/CustomTooltip/custom-tooltip.scss
- src/features/Endpoint/Endpoint.module.scss
- src/features/Endpoint/Endpoint.tsx
- src/features/dashboard/components/api-token-table/api-table.module.scss
- src/features/dashboard/components/app-register/app-register.scss
- src/features/dashboard/components/app-register/types.ts
- src/pages/endpoint.tsx
- Updated app registration error messages
- Updated app registration error message text styles
> Sandeep/dapi 764/bug fixing

- src/components/UserNavbarItem/item.desktop.tsx
Reverts deriv-com/deriv-api-docs#180
> Revert "chore: remove console log and fix pathname"

- examples/contracts_for_symbol/package.json
- examples/open_contracts/package.json
- examples/portfolio/package.json
- examples/website_status/package.json
- package.json
Reverts deriv-com/deriv-api-docs#177
> Revert "ahmed/DAPI-830/fix--rename-packages-security-fix"

- package-lock.json
- package.json
- static/front-channel.html
Added front channels, which will automatically log Deriv API out whenever user logs out in other applications like Deriv.app.
Updated auth client library to ensure we are passing in `id_token_hint` whenever we are logging out
> Adrienne / Added front channels and updated auth client

- src/components/HomePageSkeleton/HomePageSkeleton.module.scss
- src/components/HomePageSkeleton/index.tsx
- src/components/Layout/CustomLayout.tsx
- src/hooks/useHandleLogin/index.tsx
- src/hooks/useLogout/index.tsx
- src/pages/index.tsx
- src/styles/index.scss
This pull request includes various changes to enhance the user experience on the homepage by adding a skeleton loader, improving the login/logout process, and handling silent login states. The most important changes are summarized below:
* Added a new `HomePageSkeleton` component with styles to display a skeleton loader while the main content is loading. (`src/components/HomePageSkeleton/index.tsx`, `src/components/HomePageSkeleton/HomePageSkeleton.module.scss`) [[1]](diffhunk://#diff-1c2f62aacd2f58976243001ef8b15ce81a3b41801e4abac7aa4ed61aa27473efR1-R50) [[2]](diffhunk://#diff-2f6493efafa6696d9f2d913268a2ae3325ad8dd074c5a4baef0e786d205cfc2cR1-R136)
* Enhanced the `useHandleLogin` and `useLogout` hooks to include error handling and logging for OAuth2 authentication processes. …
> fix: sso loader
